### ISSUE TITLE
Status and Tracking

### ISSUE THREAD

**Issue by desbenn** [DPBandA/job-management-tracking-system#106]
- [x] Create JobTracking class and add jobStatusAndTrackingId, current and previous values, etc fields. NB: create the table for all databases. **Not done**.
- [X] Put "Tracking History" button in Tracking tab to show a table of the tracking history. **Note done**.
- [x] Implement feature to add tracking records similar to what is done status note. **Not done**.
- [x] A job acceptance option and status notes need to be mandatory when a job-entry is being set. **Not done**.
- [x] Put tracking info in a panel called "Tracking" in the job status and tracking tab.
to "waiting on client", "paused", "withdrawn by client" or "cancelled".
- [x] Create general purpose StatusNote class to for any entity with entityId field.
- [x] Status Notes should not be able to be deleted and should therefore be able to show a history of who wrote what and when what was written (based on the login credentials of the writer). See mock up from GA o GDrive. NB This feature should be enabled/disabled with a system option...add to all databases. Create the statusnote table for all databases.
- [x] Add transient header field to status note.
- [x] Add required field validation to status note dialog.
- [x] Add privileges  to add or delete status note. **Not done**.
- [x] Allow copying of the status note in job status and tracking when adding a new status note object. Or automatically copy it to the list of status notes?
- [x] Change the column widths in the status note table.
- [x] Put read only text area for the text column in the status note table. **Not done**.
