### ISSUE TITLE
Work Plan & Estimated Mileage

### ISSUE THREAD

**Issue by desbenn** [DPBandA/job-management-tracking-system#158]
#### Work Plan:
- [x] Implement the creation of work plan based on template from WR.
- [x] In the work plan, the total cost of travelling per inspector is column H plus the amount in J.
#### Estimated Mileage:
- [x] Work which is going to result in the estimated mileage being more than 1000 Km must be applied for with a pre-authorization form.
- [x] The form must be signed by the inspector and relevant supervisor.
- [x] If the work results in an estimated mileage of 1500 Km and more, the pre-authorization form must also be signed by any of the senior management staff (CEO, Director, Manager)
- [x] If mileage exceeds 1000 Km, the form should be automatically generated with the inspector’s particulars and then automatically sent to the supervisor for authorization. If the inspector exceeds 1500 Km then the form would be also escalated to senior management for authorization.
