### ISSUE TITLE
BEL: Search for all // tk, unused imports and // TODO and address them. Remove Serializable from entities since it already implemented by BusinessEntity 

### ISSUE THREAD

**Issue by desbenn** [DPBandA/job-management-tracking-system#410]
- [ ] Remove serialVersionUID from all classes
- [ ] Search for all // tk 
- [ ] Unused imports
- [ ] Addess // TODO
- [ ] Remove Serializable from entities since it already implemented by BusinessEntity
