### ISSUE TITLE
BEL: Search for all // tk, unused imports and // TODO and address them. Remove Serializable from entities since it already implemented by BusinessEntity 

### ISSUE THREAD

**Issue by desbenn** [DPBandA/job-management-tracking-system#576]
- [x] Remove serialVersionUID from all classes
- [x] Search for all // tk 
- [x] Unused imports
- [x] Addess // TODO
- [x] Remove Serializable from entities since it already implemented by BusinessEntity
